-- NOTE: This file is auto generated by ./sql-generator

-- SharedSpaceRepository.getById
select
  *
from
  "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getAllByUserId
select
  "shared_space".*
from
  "shared_space"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space"."id"
where
  "shared_space_member"."userId" = $1

-- SharedSpaceRepository.update
update "shared_space"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.remove
delete from "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getMembers
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1

-- SharedSpaceRepository.getMember
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1
  and "shared_space_member"."userId" = $2

-- SharedSpaceRepository.updateMember
update "shared_space_member"
set
  "role" = $1
where
  "spaceId" = $2
  and "userId" = $3
returning
  *

-- SharedSpaceRepository.removeMember
delete from "shared_space_member"
where
  "spaceId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getSpaceIdsForTimeline
select
  "spaceId"
from
  "shared_space_member"
where
  "userId" = $1
  and "showInTimeline" = $2

-- SharedSpaceRepository.getAssetCount
select
  count(*) as "count"
from
  "shared_space_asset"
where
  "spaceId" = $1

-- SharedSpaceRepository.removeAssets
delete from "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" in ($2)

-- SharedSpaceRepository.getMostRecentAssetId
select
  "asset"."id"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
where
  "shared_space_asset"."spaceId" = $1
  and "asset"."deletedAt" is null
order by
  "shared_space_asset"."addedAt" desc
limit
  $2

-- SharedSpaceRepository.getRecentAssets
select
  "asset"."id",
  "asset"."thumbhash"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
where
  "shared_space_asset"."spaceId" = $1
  and "asset"."deletedAt" is null
order by
  "shared_space_asset"."addedAt" desc
limit
  $2

-- SharedSpaceRepository.getLastAssetAddedAt
select
  max("addedAt") as "lastAddedAt"
from
  "shared_space_asset"
where
  "spaceId" = $1

-- SharedSpaceRepository.getNewAssetCount
select
  count(*) as "count"
from
  "shared_space_asset"
where
  "spaceId" = $1
  and "addedAt" > $2

-- SharedSpaceRepository.getLastContributor
select
  "user"."id",
  "user"."name"
from
  "shared_space_asset"
  inner join "user" on "user"."id" = "shared_space_asset"."addedById"
  and "user"."deletedAt" is null
where
  "shared_space_asset"."spaceId" = $1
  and "shared_space_asset"."addedAt" > $2
order by
  "shared_space_asset"."addedAt" desc
limit
  $3

-- SharedSpaceRepository.updateMemberLastViewed
update "shared_space_member"
set
  "lastViewedAt" = $1
where
  "spaceId" = $2
  and "userId" = $3

-- SharedSpaceRepository.getContributionCounts
select
  "addedById",
  count(*) as "count"
from
  "shared_space_asset"
where
  "spaceId" = $1
group by
  "addedById"

-- SharedSpaceRepository.getMemberActivity
select
  "addedById",
  max("addedAt") as "lastAddedAt",
  (
    select
      "ssa2"."assetId"
    from
      "shared_space_asset" as "ssa2"
    where
      "ssa2"."addedById" = "shared_space_asset"."addedById"
      and "ssa2"."spaceId" = $1
    order by
      "ssa2"."addedAt" desc
    limit
      $2
  ) as "recentAssetId"
from
  "shared_space_asset"
where
  "spaceId" = $1
group by
  "addedById"

-- SharedSpaceRepository.getMapMarkers
select
  "asset"."id",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "shared_space_asset"."spaceId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
